import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

import { groupReviewLabel } from '../src/utils/identityGroupReviewUi.js'

const page = readFileSync(new URL('../src/pages/ScanResults.jsx', import.meta.url), 'utf8')
const component = readFileSync(new URL('../src/components/SystemExplanation.jsx', import.meta.url), 'utf8')

test('group list renders an additive scannable system explanation preview', () => {
  assert.match(page, /explanation=\{group\.system_explanation\} compact/)
  assert.match(component, /Why it was surfaced:/)
})

test('group detail places complete explanation before advanced evidence', () => {
  const explanation = page.indexOf('<SystemExplanation explanation={detail.system_explanation}')
  const evidence = page.indexOf('<EvidenceSummary detail={detail}')
  assert.ok(explanation > 0)
  assert.ok(explanation < evidence)
})

test('plain explanation has an accessible hierarchy and bounded sections', () => {
  assert.match(component, /aria-label=\{heading\}/)
  assert.match(component, /Evidence to consider/)
  assert.match(component, /What to check/)
  assert.match(component, /Human review:/)
})

test('raw technical evidence remains available only under advanced disclosure', () => {
  assert.match(page, /<details><summary>Advanced relationship evidence/)
  assert.match(page, /JSON\.stringify\(evidence, null, 2\)/)
})

test('system explanation and human decision are separate product regions', () => {
  assert.match(page, /SystemExplanation/)
  assert.match(page, /<GroupReviewPanel/)
  assert.match(page, /<b>Human review:<\/b>/)
  assert.doesNotMatch(component, /createVersionedGroupReview|Save review|supersedes/)
})

test('human reviewed states remain explicit and are not generated by system explanation', () => {
  assert.match(groupReviewLabel({ reviewed: true, current_decision_type: 'CONFIRM_ALL_AS_ONE' }), /Reviewed.*all confirmed as one/)
  assert.match(groupReviewLabel({ reviewed: true, current_decision_type: 'KEEP_ALL_SEPARATE' }), /Reviewed.*kept separate/)
  assert.match(groupReviewLabel({ reviewed: true, current_decision_type: 'UNSURE' }), /Reviewed.*unsure/)
  assert.doesNotMatch(component, /CONFIRM_ALL_AS_ONE|KEEP_ALL_SEPARATE|UNSURE/)
})

test('conflict and deferred outcomes use their persisted system explanations', () => {
  assert.match(page, /explanation=\{item\.system_explanation\} heading="Why the system kept these records separate"/)
  assert.match(page, /explanation=\{item\.system_explanation\} heading="Why this identity work is deferred"/)
})

test('explanation component does not calculate scores or calibrated probabilities', () => {
  assert.doesNotMatch(component, /similarity_score|deterministic_score|confidence|probability|%/i)
})
